#!/usr/bin/env ruby

require 'net/http'
require 'nokogiri'

def main
  #html = Net::HTTP.get(URI('http://espn.go.com/mlb/standings'))
  html = File.read("raw.html")
  doc = Nokogiri::HTML(html)

  standings_tables = doc.css("table.standings")

  standings_tables.each do |table|
    league_name = table.at_css("caption")
    puts league_name
    table.search("./tr").each do |tr|
      puts tr.element_children.map(&:text).join(" ")
#      if "th" == tr.first_element_child.node_name
#        puts tr.search("./th").map(&:text).join(" ")
#      else
#        # todo
#      end
    end
  end
#  standings.search('./tr').each do |tr|
#    puts tr
#    x.format(tr)
#  end
end

class TableMaker
  def format(tr)
    send(tr['class'].split(' ').first, tr)
  end

  def stathead(tr)
    puts Divider, tr.text
  end

  def colhead(tr)
    puts Underline
    row(tr)
  end

  def oddrow(tr)
    row(tr)
  end

  def evenrow(tr)
    row(tr)
  end

  def row(tr)
    division_name, *columns = tr.search('./td').map { |td| td.text }
    division_name = division_name.ljust(15, ' ')
    columns       = columns.map { |column| column.rjust(8, ' ') }
    columns = columns.take((TermWidth - 15) / 8)
    puts "#{division_name}#{columns.join}"
  end

  TermWidth = STDOUT.tty? ? `tput cols`.to_i : 103
  Divider   = '-' * TermWidth
  Underline = '-' * TermWidth
end

main
