#!/usr/bin/env ruby

require 'net/http'
require 'nokogiri'

def main
  #html = Net::HTTP.get(URI('http://espn.go.com/mlb/standings'))
  html = File.read("raw.html")
  doc = Nokogiri::HTML(html)

  standings_tables = doc.css("table.standings")

  x = TableMaker.new
  standings_tables.each do |table|
    league_name = table.at_css("caption").text
    x.caption league_name
    table.search("./tr").each do |tr|
      if "th" == tr.first_element_child.node_name
        x.th(tr)
      else
        x.td(tr)
      end
    end
  end
end

class TableMaker
  def caption(str)
    puts Divider, str
  end

  def th(tr)
    puts Underline
    row(tr)
    puts Underline
  end

  def td(tr)
    row(tr)
  end

  def row(tr)
    columns    = tr.element_children.map { |td| td.text }
    columns    = columns.map { |column| column.rjust(8, ' ') }
    if abbr = tr.first_element_child.at_css("abbr")
      columns[0] = abbr.text.rjust(8, ' ')
    end
    columns    = columns.take((TermWidth - 15) / 8)
    puts columns.join
  end

  TermWidth = STDOUT.tty? ? `tput cols`.to_i : 103
  Divider   = '=' * TermWidth
  Underline = '-' * TermWidth
end

main
